name: 'Go modules License Checker'
author: 'oscarpicas'
description: 'Check licenses of dependencies for go projects using modules'
inputs:
  goversion:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
    required: false
    default: '1.16'
branding:
  icon: file-text
  color: green
runs:
  using: "composite"
  steps:
    - name: Backup go.mod
      run: cp go.mod go.mod.bak || true
      shell: bash
    - name: Backup go.sum
      run: cp go.sum go.sum.bak || true
      shell: bash
    - name: Set up Go version
      uses: actions/setup-go@v2
      with:
        go-version: ${{github.event.inputs.goversion}}
      id: go

    - name: Get Bobgy fork of google/go-licenses package
      run: go get github.com/Bobgy/go-licenses/v2
      shell: bash
    - name: Restore go.mod
      run: cp -f go.mod.bak go.mod || true
      shell: bash
    - name: Restore go.sum
      run: cp -f go.sum.bak go.sum || true
      shell: bash

    - name: Get licenses as csv
      run: ${{ github.action_path }}/csv.sh
      shell: bash

    - name: Run Check
      run: ${{ github.action_path }}/check.sh
      shell: bash
